### ISSUE TITLE
SignIN - Dark Mode Issues

### ISSUE THREAD

**Issue by app-generator** [app-generator/ct-black-dashboard#1]
Hello @ahmed-alii 

The rest of the sire looks good but the login page has a strange behavior. 

### Issue 1 - Content is not fitting in the page

The content on SignIn page has scroll bars 

### Issue 2 - Dark-Mode Activation

When the dark-mode is activated/deactivated the page shakes a few seconds. 

Please take a look. Ty! 

![t-black-free-dark-mode-bug](https://user-images.githubusercontent.com/51070104/189040636-31fd17e7-5037-4e68-8ac4-38a997ca758c.gif)

**Comment by ahmed-alii** [comment]
HI. Can you try loading the page in incognito mode? I will need to see how I can reproduce this issue.

**Comment by ahmed-alii** [comment]
Pushed new update for sign in page. Please review once again.
